// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNh5MseQdtq22uZH2lIR6GDYYe4MU3h2s',
    appId: '1:934750462910:android:940ed79757507351e80fef',
    messagingSenderId: '934750462910',
    projectId: 'devmob-events',
    storageBucket: 'devmob-events.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDriV6vDDQ8Ze_khOaQJeGHTe0N8JiCFUM',
    appId: '1:934750462910:ios:0cfb16503d1c8361e80fef',
    messagingSenderId: '934750462910',
    projectId: 'devmob-events',
    storageBucket: 'devmob-events.firebasestorage.app',
    iosBundleId: 'com.example.devmobDeveloppement',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7l9kvr6Fr0uIWN3uFdw1ksEI1dm5zSZs',
    appId: '1:934750462910:web:3adc52d0db794ef2e80fef',
    messagingSenderId: '934750462910',
    projectId: 'devmob-events',
    authDomain: 'devmob-events.firebaseapp.com',
    storageBucket: 'devmob-events.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDriV6vDDQ8Ze_khOaQJeGHTe0N8JiCFUM',
    appId: '1:934750462910:ios:0cfb16503d1c8361e80fef',
    messagingSenderId: '934750462910',
    projectId: 'devmob-events',
    storageBucket: 'devmob-events.firebasestorage.app',
    iosBundleId: 'com.example.devmobDeveloppement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7l9kvr6Fr0uIWN3uFdw1ksEI1dm5zSZs',
    appId: '1:934750462910:web:192f84996c578731e80fef',
    messagingSenderId: '934750462910',
    projectId: 'devmob-events',
    authDomain: 'devmob-events.firebaseapp.com',
    storageBucket: 'devmob-events.firebasestorage.app',
  );
}
